routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

// Home
Route::get('/', [HomeController::class, 'index'])->name('home');

// User
Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', [UserController::class, 'profile'])->name('done');
    Route::get('pending', [UserController::class, 'profile'])->name('pending');
    Route::get('products', [UserController::class, 'profile'])->name('products');
    Route::get('questions', [UserController::class, 'profile'])->name('questions');
    Route::get('answers', [UserController::class, 'profile'])->name('answers');
    Route::get('following', [UserController::class, 'profile'])->name('following');
    Route::get('followers', [UserController::class, 'profile'])->name('followers');
});

// Settings
Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
    Route::get('', [UserController::class, 'profileSettings'])->name('profile');
    Route::get('account', [UserController::class, 'accountSettings'])->name('account');
    Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
    Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
    Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
    Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
    Route::get('api', [UserController::class, 'apiSettings'])->name('api');
    Route::get('export', [UserController::class, 'exportAccount'])->name('export');
    Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
});

// Notifications
Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
    Route::view('', 'notifications.unread')->name('unread');
    Route::view('all', 'notifications.all')->name('all');
});

// Suspended
Route::get('suspended', [UserController::class, 'suspended'])->name('suspended');

// Mention
Route::group(['prefix' => 'mention', 'middleware' => ['auth']], function () {
    Route::get('users', [UserController::class, 'mention']);
    Route::get('products', [ProductController::class, 'mention']);
});

// Avatar
Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

// Webhooks
Route::group(['prefix' => 'webhook'], function () {
    Route::post('web/{token}', [WebhookController::class, 'web']);
});

// Product
Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', [ProductController::class, 'profile'])->name('done');
    Route::get('pending', [ProductController::class, 'profile'])->name('pending');
    Route::get('updates', [ProductController::class, 'profile'])->name('updates');
});

// Products
Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('', [ProductController::class, 'newest'])->name('newest');
    Route::get('launched', [ProductController::class, 'launched'])->name('launched');
});

// Question
Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
    Route::get('{id}', [QuestionController::class, 'question'])->name('question');
});

// Questions
Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
    Route::get('', [QuestionController::class, 'newest'])->name('newest');
    Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
    Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
});

// Search
Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
    Route::get('', [SearchController::class, 'search'])->name('home');
    Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
    Route::get('comments', [SearchController::class, 'comments'])->name('comments');
    Route::get('questions', [SearchController::class, 'questions'])->name('questions');
    Route::get('answers', [SearchController::class, 'answers'])->name('answers');
    Route::get('products', [SearchController::class, 'products'])->name('products');
    Route::get('users', [SearchController::class, 'users'])->name('users');
});

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
    Route::get('users', [AdminController::class, 'users'])->name('users');
    Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
});

// Patron
Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
    Route::get('', [PatronController::class, 'patron'])->name('home');
});

// Paddle Integration
Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

// Dark mode
Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

// Single Task and comment
Route::group(['prefix' => 'task'], function () {
    Route::get('{id}', [TaskController::class, 'task'])->name('task');
    Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
});

// Zen mode tasks
Route::get('tasks', [TaskController::class, 'tasks'])->name('tasks')->middleware('auth');

// Pages
Route::view('about', 'pages.about')->name('about');
Route::view('reputation', 'pages.reputation')->name('reputation');
Route::view('terms', 'pages.terms')->name('terms');
Route::view('privacy', 'pages.privacy')->name('privacy');
Route::view('security', 'pages.security')->name('security');
Route::view('sponsors', 'pages.sponsors')->name('sponsors');
Route::get('open', 'PagesController@open')->name('open');
Route::get('deals', 'PagesController@deals')->name('deals');

// https://web.dev/change-password-url
Route::get('.well-known/change-password', function () {
    return redirect()->route('user.settings.password');
});

// Sitemaps
Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

// Status
Route::group(['prefix' => 'status'], function () {
    Route::get('ping', [StatusController::class, 'ping']);
    Route::get('redis', [StatusController::class, 'redis']);
    Route::get('memcached', [StatusController::class, 'memcached']);
});

resources/views/admin/nav.blade.php
<ul class="nav nav-pills justify-content-center mb-3">
    <li class="nav-item">
        <a class="nav-link active" href="{{ route('admin.users') }}">Users</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Products</a>
    </li>
</ul>

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('pageTitle', 'Admin - Users ·')
@section('title', 'Admin - Users ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="container">
            @include('admin.nav')
            <div class="card">
                <div class="card-header h6 pt-3 pb-3">
                    <div class="h5">Users</div>
                    <span class="font-weight-bold">{{ $count }}</span>
                    total users
                </div>
                <div class="table-responsive">
                    <table class="table text-dark">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Avatar</th>
                                <th scope="col">Name</th>
                                <th scope="col">Username</th>
                                <th scope="col">Email</th>
                                <th scope="col">Patron</th>
                                <th scope="col">Last IP</th>
                                <th scope="col">Via</th>
                                <th scope="col">Last active</th>
                                <th scope="col">More</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)
                            <tr>
                                <th>{{ $user->id }}</th>
                                <td>
                                    <img class="avatar-30 rounded-circle mr-2" src="{{ $user->avatar }}" />
                                </td>
                                <td class="font-weight-bold">
                                    @if (!$user->firstname and !$user->lastname)
                                    <span class="small font-weight-bold text-black-50">Not Set</span>
                                    @else
                                    {{ $user->firstname.' '.$user->lastname }}
                                    @endif
                                    @if ($user->isVerified)
                                        <i class="fa fa-check-circle ml-1 text-primary" data-toggle="tooltip" data-placement="right" title="Verified"></i>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{ route('user.done', ['username' => $user->username]) }}" target="_blank">
                                        {{ '@'.$user->username }}
                                    </a>
                                </td>
                                <td>
                                    {{ $user->email }}
                                    @if ($user->hasVerifiedEmail())
                                    <i class="fa fa-check text-success ml-1" title="Email Verified"></i>
                                    @else
                                    <i class="fa fa-times text-danger ml-1" title="Email not Verified"></i>
                                    @endif
                                </td>
                                <td>
                                    @if (!$user->isPatron)
                                    <span>
                                        ❌
                                    </span>
                                    @else
                                    <span>
                                        💰
                                        @if ($user->patron)
                                        🤝
                                        @else
                                        🎁
                                        @endif
                                    </span>
                                    @endif
                                </td>
                                <td>
                                    @if ($user->lastIP)
                                    <a class="font-monospace" href="https://ipinfo.io/{{ $user->lastIP }}" title="{{ $user->lastIP }}" target="_blank">
                                        {{ Str::limit($user->lastIP, 15, '..') }}
                                    </a>
                                    @else
                                    <span class="small font-weight-bold text-black-50">Not logged</span>
                                    @endif
                                </td>
                                <td>
                                    @if ($user->provider === 'google')
                                        <i class="fa fa-google text-danger"></i>
                                    @elseif ($user->provider === 'twitter')
                                        <i class="fa fa-twitter text-info"></i>
                                    @else
                                        <i class="fa fa-globe text-success"></i>
                                    @endif
                                </td>
                                <td title="{{ Carbon::parse($user->last_active)->format('M d, Y g:i A') }}">
                                    @if ($user->last_active)
                                    @if (strtotime(Carbon::now()) - strtotime($user->last_active) <= 5)
                                    <span class="font-weight-bold text-success">active</span>
                                    @else
                                    {{ Carbon::parse($user->last_active)->diffForHumans() }}
                                    @endif
                                    @else
                                    <span class="small font-weight-bold text-black-50">Not Set</span>
                                    @endif
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">
                                            More
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-check mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->tasks()->count('id') }}</span> Tasks
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-comment mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->comments()->count('id') }}</span> Comments
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-question-circle mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->questions()->count('id') }}</span> Questions
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-comments mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->answers()->count('id') }}</span> Answers
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-box-open mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->ownedProducts('id')->count() }}</span> Products
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-handshake mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->products()->count() }}</span> Membership
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-bell mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->notifications()->count('id') }}</span> Notifications
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-anchor mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->webhooks()->count('id') }}</span> Webhooks
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item">
                                                    <i class="fa fa-user-clock mr-1"></i>
                                                    <span class="font-weight-bold">{{ $user->timezone }}</span>
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item" title="{{ Carbon::parse($user->updated_at)->format('M d, Y g:i A') }}">
                                                    <i class="fa fa-calendar mr-1"></i>
                                                    <span class="font-weight-bold">{{ Carbon::parse($user->updated_at)->format('M d, Y') }}</span>
                                                </span>
                                            </li>
                                            <li>
                                                <span class="dropdown-item" title="{{ Carbon::parse($user->created_at)->format('M d, Y g:i A') }}">
                                                    <i class="fa fa-calendar mr-1"></i>
                                                    <span class="font-weight-bold">{{ Carbon::parse($user->created_at)->format('M d, Y') }}</span>
                                                    @if ($user->created_at->diffInDays(Carbon::today()) < 7)
                                                        🆕
                                                    @endif
                                                </span>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $users->links() }}
            </div>
        </div>
    </div>
</div>
@endsection