routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

// Home
Route::get('/', [HomeController::class, 'index'])->name('home');

// User
Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', [UserController::class, 'profile'])->name('done');
    Route::get('pending', [UserController::class, 'profile'])->name('pending');
    Route::get('products', [UserController::class, 'profile'])->name('products');
    Route::get('questions', [UserController::class, 'profile'])->name('questions');
    Route::get('answers', [UserController::class, 'profile'])->name('answers');
    Route::get('following', [UserController::class, 'profile'])->name('following');
    Route::get('followers', [UserController::class, 'profile'])->name('followers');
});

// Settings
Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
    Route::get('', [UserController::class, 'profileSettings'])->name('profile');
    Route::get('account', [UserController::class, 'accountSettings'])->name('account');
    Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
    Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
    Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
    Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
    Route::get('api', [UserController::class, 'apiSettings'])->name('api');
    Route::get('export', [UserController::class, 'exportAccount'])->name('export');
    Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
});

// Notifications
Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
    Route::view('', 'notifications.unread')->name('unread');
    Route::view('all', 'notifications.all')->name('all');
});

// Suspended
Route::get('suspended', [UserController::class, 'suspended'])->name('suspended');

// Mention
Route::group(['prefix' => 'mention', 'middleware' => ['auth']], function () {
    Route::get('users', [UserController::class, 'mention']);
    Route::get('products', [ProductController::class, 'mention']);
});

// Avatar
Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

// Webhooks
Route::group(['prefix' => 'webhook'], function () {
    Route::post('web/{token}', [WebhookController::class, 'web']);
});

// Product
Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', [ProductController::class, 'profile'])->name('done');
    Route::get('pending', [ProductController::class, 'profile'])->name('pending');
    Route::get('updates', [ProductController::class, 'profile'])->name('updates');
});

// Products
Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('', [ProductController::class, 'newest'])->name('newest');
    Route::get('launched', [ProductController::class, 'launched'])->name('launched');
});

// Question
Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
    Route::get('{id}', [QuestionController::class, 'question'])->name('question');
});

// Questions
Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
    Route::get('', [QuestionController::class, 'newest'])->name('newest');
    Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
    Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
});

// Search
Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
    Route::get('', [SearchController::class, 'search'])->name('home');
    Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
    Route::get('comments', [SearchController::class, 'comments'])->name('comments');
    Route::get('questions', [SearchController::class, 'questions'])->name('questions');
    Route::get('answers', [SearchController::class, 'answers'])->name('answers');
    Route::get('products', [SearchController::class, 'products'])->name('products');
    Route::get('users', [SearchController::class, 'users'])->name('users');
});

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
    Route::get('users', [AdminController::class, 'users'])->name('users');
    Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
});

// Patron
Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
    Route::get('', [PatronController::class, 'patron'])->name('home');
});

// Paddle Integration
Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

// Dark mode
Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

// Single Task and comment
Route::group(['prefix' => 'task'], function () {
    Route::get('{id}', [TaskController::class, 'task'])->name('task');
    Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
});

// Zen mode tasks
Route::get('tasks', [TaskController::class, 'tasks'])->name('tasks')->middleware('auth');

// Pages
Route::view('about', 'pages.about')->name('about');
Route::view('reputation', 'pages.reputation')->name('reputation');
Route::view('terms', 'pages.terms')->name('terms');
Route::view('privacy', 'pages.privacy')->name('privacy');
Route::view('security', 'pages.security')->name('security');
Route::view('sponsors', 'pages.sponsors')->name('sponsors');
Route::get('open', 'PagesController@open')->name('open');
Route::get('deals', 'PagesController@deals')->name('deals');

// https://web.dev/change-password-url
Route::get('.well-known/change-password', function () {
    return redirect()->route('user.settings.password');
});

// Sitemaps
Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

// Status
Route::group(['prefix' => 'status'], function () {
    Route::get('ping', [StatusController::class, 'ping']);
    Route::get('redis', [StatusController::class, 'redis']);
    Route::get('memcached', [StatusController::class, 'memcached']);
});

app/Http/Livewire/User/Moderator.php
<?php

namespace App\Http\Livewire\User;

use App\Models\User;
use App\Notifications\PatronGifted;
use App\Notifications\TelegramLogger;
use App\Notifications\UserVerified;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;

class Moderator extends Component
{
    public $user;

    public function mount($user)
    {
        $this->user = $user;
    }

    public function enrollBeta()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->isBeta = ! $this->user->isBeta;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isBeta) {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is enrolled to beta by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is un-enrolled from beta by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function enrollStaff()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $this->user->isStaff = ! $this->user->isStaff;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isStaff) {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is enrolled as staff by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is un-enrolled from staff by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function enrollDeveloper()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->isDeveloper = ! $this->user->isDeveloper;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isDeveloper) {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is enrolled as contributor by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is un-enrolled from contributor by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function privateUser()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $this->user->isPrivate = ! $this->user->isPrivate;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isPrivate) {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is marked as private user by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is marked as public user by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function flagUser()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $this->user->isFlagged = ! $this->user->isFlagged;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isFlagged) {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is flagged by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is un-flagged by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function suspendUser()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $this->user->isSuspended = ! $this->user->isSuspended;
            if ($this->user->isSuspended) {
                $this->user->isFlagged = true;
            } else {
                $this->user->isFlagged = false;
            }
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isSuspended) {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is suspended and flagged by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is un-suspended and un-flagged by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function enrollPatron()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->isPatron = ! $this->user->isPatron;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isPatron) {
                $this->user->notify(new PatronGifted(true));
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is enrolled as patron by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is un-enrolled from patron by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function verifyUser()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->isVerified = ! $this->user->isVerified;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isVerified) {
                $this->user->notify(new UserVerified(true));
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is verified by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is un-verified by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function enrollDarkMode()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->darkMode = ! $this->user->darkMode;
            $this->user->timestamps = false;
            $this->user->save();
            if ($this->user->isPatron) {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is enabled dark mode by @'.Auth::user()->username));
            } else {
                $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".$this->user->username.' is disabled dark mode by @'.Auth::user()->username));
            }
        } else {
            return false;
        }
    }

    public function masquerade()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".Auth::user()->username.' is masqueraded into @'.$this->user->username));
            Auth::loginUsingId($this->user->id);

            return redirect()->route('home');
        } else {
            return false;
        }
    }

    public function deleteTasks()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $user = User::find($this->user->id);
            $user->timestamps = false;
            foreach ($user->tasks as $task) {
                Storage::delete($task->image);
            }
            $user->tasks()->delete();
            $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".Auth::user()->username.' deleted all tasks made by @'.$this->user->username));

            return redirect()->route('user.done', ['username' => $this->user->username]);
        } else {
            return false;
        }
    }

    public function deleteComments()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $user = User::find($this->user->id);
            $user->timestamps = false;
            $user->comment()->delete();
            $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".Auth::user()->username.' deleted all comments made by @'.$this->user->username));

            return redirect()->route('user.done', ['username' => $this->user->username]);
        } else {
            return false;
        }
    }

    public function deleteQuestions()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $user = User::find($this->user->id);
            $user->timestamps = false;
            $user->questions()->delete();
            $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".Auth::user()->username.' deleted all questions made by @'.$this->user->username));

            return redirect()->route('user.done', ['username' => $this->user->username]);
        } else {
            return false;
        }
    }

    public function deleteAnswers()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $user = User::find($this->user->id);
            $user->timestamps = false;
            $user->answers()->delete();
            $this->user->notify(new TelegramLogger("*🚨 Mod Event 🚨*\n\n@".Auth::user()->username.' deleted all answers made by @'.$this->user->username));

            return redirect()->route('user.done', ['username' => $this->user->username]);
        } else {
            return false;
        }
    }

    public function deleteProducts()
    {

resources/views/user/answers.blade.php
@extends('layouts.app')

@php
if ($user->lastname and $user->lastname) {
    $name = '('.$user->firstname.' '.$user->lastname.')';
} else if ($user->firstname) {
    $name = '('.$user->firstname.')';
} else {
    $name = '';
}
@endphp

@section('pageTitle', $user->username.' '.$name.' / Answers ·')
@section('title', $user->username.' '.$name.' / Answers ·')
@section('title', $user->username.' ('.$name.') ·')
@section('description', $user->bio)
@section('image', $user->avatar)
@section('url', url()->current())

@section('content')
<div class="container">
    @include('user.profile')
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            @livewire('user.answers', [
                'user' => $user
            ])
        </div>
        @include('user.sidebar')
    </div>
</div>
@endsection

resources/views/user/done.blade.php
@extends('layouts.app')

@php
if ($user->lastname and $user->lastname) {
    $name = '('.$user->firstname.' '.$user->lastname.')';
} else if ($user->firstname) {
    $name = '('.$user->firstname.')';
} else {
    $name = '';
}
@endphp

@section('pageTitle', $user->username.' '.$name.' ·')
@section('title', $user->username.' '.$name.' ·')
@section('description', $user->bio)
@section('image', $user->avatar)
@section('url', url()->current())

@section('content')
<div class="container">
    @include('user.profile')
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            @auth
            @if (Auth::id() === $user->id && !$user->isFlagged)
                @livewire('create-task')
            @endif
            @endauth
            @if (
                !$user->isPrivate or
                Auth::id() === $user->id or
                Auth::check() && Auth::user()->staffShip
            )
            @livewire('user.tasks', [
                'type' => 'user.done',
                'user' => $user,
                'page' => 1,
                'perPage' => 3
            ])
            @else
            <x-empty icon="lock" text="All tasks are private" />
            @endif
        </div>
        @include('user.sidebar')
    </div>
</div>
@endsection

resources/views/user/profile.blade.php
<div class="card">
    @auth
    @if (Auth::user()->isStaff && $user->isFlagged)
        <div class="p-4 pb-0">
            <div class="alert alert-danger alert-dismissible">
                This user is flagged
                {{ $user->isSuspended ? 'and suspended' : '' }}
                as spammy!
            </div>
        </div>
    @endif
    @endauth
    <div class="row">
        <div class="col-md-7">
            <div class="card-body d-flex align-items-center">
                <a href="{{ $user->avatar }}" data-lightbox="{{ $user->avatar }}" data-title="{{ '@'.$user->username }}'s Avatar">
                    <img class="rounded-circle avatar-120" src="{{ $user->avatar }}" />
                </a>
                <div class="ml-4">
                    <div class="h5 mb-0">
                        @if ($user->firstname or $user->lastname)
                            {{ $user->firstname }}{{ ' '.$user->lastname }}
                        @else
                            {{ $user->username }}
                        @endif
                        @auth
                        @endauth
                        @if ($user->isPrivate)
                            <i class="ml-2 fa fa-lock text-primary" data-toggle="tooltip" data-placement="right" title="Private Profile"></i>
                        @endif
                        @if ($user->isVerified)
                            <i class="ml-2 fa fa-check-circle text-primary" data-toggle="tooltip" data-placement="right" title="Verified"></i>
                        @endif
                        @if ($user->isPatron)
                            <a class="ml-2 small" href="{{ route('patron.home') }}" data-toggle="tooltip" data-placement="right" title="Patron">
                                {{ Emoji::handshake() }}
                            </a>
                        @endif
                        @auth
                        @if ($user->isFollowing(Auth::user()))
                            <span class="ml-2 badge bg-light text-black-50">Follows you</span>
                        @endif
                        @if (Auth::user()->staffShip)
                            <span class="ml-2 text-secondary small">#{{ $user->id }}</span>
                        @endif
                        @endauth
                    </div>
                    <div class="text-black-50 mb-2">
                        {{ "@" . $user->username }}
                    </div>
                    @livewire('user.follow', [
                        'user' => $user
                    ])
                    @if ($user->bio)
                    <div class="mt-3">
                        {{ $user->bio }}
                    </div>
                    @endif
                    <div class="small mt-3">
                        <span>
                            <i class="fa fa-calendar-alt mr-1 text-black-50"></i>
                            Joined {{ Carbon::parse($user->created_at)->format("F Y") }}
                        </span>
                        @if ($user->location)
                        <span class="ml-3">
                            <a class="text-dark" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/{{ urlencode($user->location) }}">
                                <i class="fa fa-compass mr-1 text-black-50"></i>
                                {{ $user->location }}
                            </a>
                        </span>
                        @endif
                        @if ($user->company)
                        <span class="ml-3">
                            <i class="fa fa-briefcase mr-1 text-black-50"></i>
                            {{ $user->company }}
                        </span>
                        @if ($user->isStaff)
                        <span class="badge rounded-pill bg-primary ml-1">Staff</span>
                        @endif
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card-body">
                <div class="h5">Highlights</div>
                <div class="mt-3">
                    <div>
                        <span class="font-weight-bold">{{ Emoji::fire() }} {{ number_format($user->getPoints()) }}</span>
                        {{ $user->getPoints(true) < 2 ? 'Reputation' : 'Reputations' }}
                        <x-beta background="light" />
                    </div>
                    @if (Auth::check() && Auth::id() === $user->id)
                    <div class="mt-2">
                        <span>{{ Emoji::blossom() }} You are a</span>
                        <span class="font-weight-bold">{{ count($level) === 0 ? 'Beginner' : $level->last()->name }}</span>
                        <x-beta background="light" />
                    </div>
                    @else
                    <div class="mt-2">
                        <span>{{ Emoji::blossom() }} {{ $user->username }} is a</span>
                        <span class="font-weight-bold">{{ count($level) === 0 ? 'Beginner' : $level->last()->name }}</span>
                        <x-beta background="light" />
                    </div>
                    @endif
                    @if ($user->isBeta)
                    <div class="mt-2">
                        <span class="font-weight-bold">{{ Emoji::testTube() }} Beta Program Member</span>
                    </div>
                    @endif
                    @if ($user->isDeveloper)
                    <div class="mt-2">
                        <span class="font-weight-bold">{{ Emoji::checkBoxWithCheck() }} Taskord Contributor</span>
                    </div>
                    @endif
                </div>
            </div>  
        </div>
    </div>
    <div class="card-footer text-muted">
        @if (
            !$user->isPrivate or
            Auth::id() === $user->id or
            Auth::check() && Auth::user()->staffShip
        )
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.done', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.done') text-primary @endif">Done</span>
            <span class="small font-weight-normal text-black-50">{{ number_format($done_count) }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.pending', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.pending') text-primary @endif">Pending</span>
            <span class="small font-weight-normal text-black-50">{{ number_format($pending_count) }}</span>
        </a>
        @endif
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.products', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.products') text-primary @endif">Products</span>
            <span class="small font-weight-normal text-black-50">{{ number_format($product_count) }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.questions', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.questions') text-primary @endif">Questions</span>
            <span class="small font-weight-normal text-black-50">{{ number_format($question_count) }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.answers', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.answers') text-primary @endif">Answers</span>
            <span class="small font-weight-normal text-black-50">{{ number_format($answer_count) }}</span>
        </a>
        @auth
        @if (Auth::user()->staffShip)
        <a class="text-dark font-weight-bold mr-4" href="">
            Stats
        </a>
        @endif
        @endauth
    </div>
</div>

resources/views/user/sidebar.blade.php
<div class="col-sm">
    @auth
    @if (Auth::user()->staffShip)
        @livewire('user.moderator', [
            'user' => $user
        ])
    @endif
    @endauth
    @if ($user->sponsor)
    <div class="card mb-4">
        <div class="card-header">
            Sponsor
        </div>
        <div class="card-body">
            <a class="btn btn-block btn-outline-primary" href="{{ $user->sponsor }}" target="_blank">
                <img class="rounded sponsor-icon mr-1" rel="preload" src="https://external-content.duckduckgo.com/ip3/{{ parse_url($user->sponsor)['host'] }}.ico" />
                <span class="font-weight-bold">Sponsor {{ '@'.$user->username }}</span>
            </a>
        </div>
    </div>
    @endif
    @if ($user->website or $user->twitter or $user->twitch or $user->telegram or $user->github or $user->youtube)
    <div class="card mb-4">
        <div class="card-header">
            Social
        </div>
        <ul class="list-group list-group-flush">
            @if ($user->website)
            <a class="list-group-item link-dark" href="{{ $user->website }}" target="_blank">
                <i class="fa fa-link mr-1"></i>
                {{ Helper::removeProtocol($user->website) }}
            </a>
            @endif
            @if ($user->twitter)
            <a class="list-group-item link-dark" href="https://twitter.com/{{ $user->twitter }}" target="_blank">
                <i class="fa fa-twitter mr-1"></i>
                {{ $user->twitter }}
            </a>
            @endif
            @if ($user->twitch)
            <a class="list-group-item link-dark" href="https://twitch.tv/{{ $user->twitch }}" target="_blank">
                <i class="fa fa-twitch mr-1"></i>
                {{ $user->twitch }}
            </a>
            @endif
            @if ($user->telegram)
            <a class="list-group-item link-dark" href="https://t.me/{{ $user->telegram }}" target="_blank">
                <i class="fa fa-telegram mr-1"></i>
                {{ $user->telegram }}
            </a>
            @endif
            @if ($user->github)
            <a class="list-group-item link-dark" href="https://github.com/{{ $user->github }}" target="_blank">
                <i class="fa fa-github mr-1"></i>
                {{ $user->github }}
            </a>
            @endif
            @if ($user->youtube)
            <a class="list-group-item link-dark" href="https://youtube.com/{{ $user->youtube }}" target="_blank">
                <i class="fa fa-youtube mr-1"></i>
                {{ $user->youtube }}
            </a>
            @endif
        </ul>
    </div>
    @endif
    <div class="card mb-4">
        <div class="card-header">
            Products
        </div>
        <ul class="list-group list-group-flush">
            @if (count($user->ownedProducts->merge($user->products)) === 0)
            <x-empty icon="box-open" text="No products made!" />
            @endif
            @foreach ($user->ownedProducts->merge($user->products)->take(5) as $product)
            <li class="list-group-item">
                <a href="{{ route('product.done', ['slug' => $product->slug]) }}">
                    <img class="rounded avatar-30 mt-1 ml-2" src="{{ $product->avatar }}" height="50" width="50" />
                </a>
                <a href="{{ route('product.done', ['slug' => $product->slug]) }}" class="ml-2 mr-2 align-text-top font-weight-bold text-dark">
                    {{ $product->name }}
                </a>
            </li>
            @endforeach
        </ul>
        @if (count($user->ownedProducts->merge($user->products)) > 5)
        <div class="card-footer">
            <a class="font-weight-bold" href="{{ route('user.products', ['username' => $user->username]) }}">
                {{ count($user->ownedProducts) + count($user->products) - 5 }} more Products
            </a>
        </div>
        @endif
    </div>
    <x-footer />
</div>